### ISSUE TITLE
Histogram fails to render in Jupyter notebook on Travis

### ISSUE THREAD

**Issue by tdhopper** [bokeh/bkcharts#75]
I'm getting this error on [TravisCI](https://travis-ci.org/tdhopper/pythonplot.com/builds/247215019): 

```
jupyter nbconvert --to notebook --execute "Examples.ipynb" --output "Examples.04da486.ipynb"

[NbConvertApp] Converting notebook Examples.ipynb to notebook

[NbConvertApp] Executing notebook with kernel: python3

[NbConvertApp] ERROR | Error while converting 'Examples.ipynb'

Traceback (most recent call last):

  File "/home/travis/miniconda/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 381, in export_single_notebook

    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)

  File "/home/travis/miniconda/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 172, in from_filename

    return self.from_file(f, resources=resources, **kw)

  File "/home/travis/miniconda/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 190, in from_file

    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)

  File "/home/travis/miniconda/lib/python3.6/site-packages/nbconvert/exporters/notebook.py", line 31, in from_notebook_node

    nb_copy, resources = super(NotebookExporter, self).from_notebook_node(nb, resources, **kw)

  File "/home/travis/miniconda/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 132, in from_notebook_node

    nb_copy, resources = self._preprocess(nb_copy, resources)

  File "/home/travis/miniconda/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 309, in _preprocess

    nbc, resc = preprocessor(nbc, resc)

  File "/home/travis/miniconda/lib/python3.6/site-packages/nbconvert/preprocessors/base.py", line 47, in __call__

    return self.preprocess(nb,resources)

  File "/home/travis/miniconda/lib/python3.6/site-packages/nbconvert/preprocessors/execute.py", line 242, in preprocess

    nb, resources = super(ExecutePreprocessor, self).preprocess(nb, resources)

  File "/home/travis/miniconda/lib/python3.6/site-packages/nbconvert/preprocessors/base.py", line 70, in preprocess

    nb.cells[index], resources = self.preprocess_cell(cell, resources, index)

  File "/home/travis/miniconda/lib/python3.6/site-packages/nbconvert/preprocessors/execute.py", line 275, in preprocess_cell

    raise CellExecutionError(msg)

nbconvert.preprocessors.execute.CellExecutionError: An error occurred while executing the following cell:

------------------

p = charts.Histogram(mpg, 

                     values='cty',

                     bins=12

                    )

Image(export_png(p))

------------------



WebDriverException: Message: {"errorMessage":"'undefined' is not an object (evaluating 'window.Bokeh.documents')","request":{"headers":{"Accept":"application/json","Accept-Encoding":"identity","Connection":"close","Content-Length":"393","Content-Type":"application/json;charset=UTF-8","Host":"127.0.0.1:43357","User-Agent":"Python http auth"},"httpVersion":"1.1","method":"POST","post":"{\"script\": \"\\n    // add private window prop to check that render is complete\\n    window._bokeh_render_complete = false;\\n    function done() {\\n      window._bokeh_render_complete = true;\\n    }\\n\\n    var doc = window.Bokeh.documents[0];\\n\\n    if (doc.is_idle)\\n      done();\\n    else\\n      doc.idle.connect(done);\\n    \", \"args\": [], \"sessionId\": \"2c25a020-5aa0-11e7-8a80-69b54a60bad9\"}","url":"/execute","urlParsed":{"anchor":"","query":"","file":"execute","directory":"/","path":"/execute","relative":"/execute","port":"","host":"","password":"","user":"","userInfo":"","authority":"","protocol":"","source":"/execute","queryKey":{},"chunks":["execute"]},"urlOriginal":"/session/2c25a020-5aa0-11e7-8a80-69b54a60bad9/execute"}}

Screenshot: available via screen





make: *** [run_nb] Error 1
```

I can run the same example on my Mac and it works fine. 

Any idea what is going wrong?

**Comment by tdhopper** [comment]
Here's a striped down version: https://travis-ci.org/tdhopper/pythonplot.com/builds/247233785

Failing to generate this notebook: https://github.com/tdhopper/pythonplot.com/blob/c72b2a1431807fe60b616b0002e07bdd47b7f948/Examples.ipynb

**Comment by bryevdv** [comment]
No idea, but I doubt this is related to `bkcharts` specifically. Can you make an issue on the main `bokeh` repo, with a title along the lines of "SVG export fails to render in nbconvert"? If possible with an example that just makes a trivial plot with `bokeh.plotting`?

FYI `bkcharts` is essentially unmaintained at this particular point in time. I'd highly recommend checking out Holoviews as an much more active and supported very high level interface on top of bokeh: 

http://build.holoviews.org/gallery/index.html

**Comment by bryevdv** [comment]
ping @canavandl
